FROM mcr.microsoft.com/mssql/server:2022-latest

# Працюємо під root, щоб мати права на apt-get
USER root

# Встановлюємо sqlcmd (mssql-tools)
RUN apt-get update && \
    apt-get install -y curl gnupg && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev && \
    rm -rf /var/lib/apt/lists/*

# Додаємо sqlcmd у PATH
ENV PATH="$PATH:/opt/mssql-tools/bin"

# Повертаємо користувача назад
USER mssql

# Запуск стандартного entrypoint
CMD ["/opt/mssql/bin/sqlservr"]
