version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "MyNewStrongP@ss1"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1'"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: PersonalProjectNotes/Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: "Server=mssql_db,1433;Database=PersonalProjectNotesDB;User Id=sa;Password=MyNewStrongP@ss1;TrustServerCertificate=True;"

    ports:
      - "5000:8080"
    networks:
      - app-network

  frontend:
    build:
      context: "E:/MyNotesProjectFront"
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

volumes:
  mssql-data:

networks:
  app-network:
    driver: bridge
