<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PersonalProjectNotes.Data\PersonalProjectNotes.Data.csproj" />
    <ProjectReference Include="..\PersonalProjectNotes.Domain\PersonalProjectNotes.Domain.csproj" />
  </ItemGroup>

</Project>
